spring.application.name=backend


spring.datasource.url=jdbc:postgresql://db.potwumjlppnyfbkdyagw.supabase.co:5432/postgres?sslmode=require

spring.datasource.username=postgres

spring.datasource.password=pafSliit123

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
